# Generated by Django 4.2.7 on 2023-11-27 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_recipe_ingredients_recipe_servings_recipe_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
