# Generated by Django 4.2.7 on 2023-11-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_recipe_bookmarks'),
        ('main_app', '0003_review'),
    ]

    operations = [
    ]
