# Generated by Django 4.2.7 on 2023-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_recipe_appliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='appliance',
            field=models.CharField(choices=[('Air Fryer', 'Air Fryer'), ('Microwave', 'Microwave'), ('Oven', 'Oven'), ('Pressure Cooker', 'Pressure Cooker'), ('Slow Cooker', 'Slow Cooker'), ('Stove', 'Stove')], max_length=20, null=True),
        ),
    ]
