# Generated by Django 4.2.7 on 2023-11-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='appliances',
            field=models.CharField(blank=True, choices=[('Air Fryer', 'Air Fryer'), ('Microwave', 'Microwave'), ('Oven', 'Oven'), ('Pressure Cooker', 'Pressure Cooker'), ('Slow Cooker', 'Slow Cooker'), ('Stove', 'Stove')], max_length=100, null=True),
        ),
    ]
