# Generated by Django 4.2.7 on 2023-11-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_recipe_appliances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='appliances',
        ),
    ]
