# Generated by Django 4.2.7 on 2023-11-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_recipe_appliance'),
        ('main_app', '0007_remove_recipe_appliances'),
    ]

    operations = [
    ]
